### ISSUE TITLE
Does not build with the std. instructions

### ISSUE THREAD

**Issue by MarcusE1W** [Dublo/LightTable-forked#3]
Hi.

Great you try to get LightTable working gain. I really liked to use it, but recently it's broken..

I tried to build your fork with the "standard" instructions for lighttable on Archlinux.
https://github.com/Dublo/LightTable-forked/blob/master/doc/developer-install.md

Dependencies:
- Leiningen 2.x
- node.js and npm
- git

I use openjdk 11 (came automatically)

And then build:
```
$ git clone https://github.com/Dublo/LightTable-forked
$ cd LightTable
$ script/build.sh
```

I get this error message during build:
```
Retrieving fetch/fetch/0.3.0/fetch-0.3.0.jar from clojars
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
Exception in thread "main" java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter, compiling:(cljs/closure.clj:1:1)
	at clojure.lang.Compiler.load(Compiler.java:7391)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
.
.
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at clojure.lang.DynamicClassLoader.findClass(DynamicClassLoader.java:69)
.
.
```

Do you have any advise how I could get it build ?

**Comment by prertik** [comment]
Hi. Thanks for writing a clear issue description. I'll look into this in the afternoon(GMT+5.45). I had been AFK for a few days. There is still a lot of work left in LT-forked before a version release.

**Comment by prertik** [comment]
Hi. So, I have fixed this issue here: [3b887ab](https://github.com/Dublo/LightTable-forked/pull/2/commits/3b887ab2155be85806f29f26905d02453ffce078)

**Comment by MarcusE1W** [comment]
It works :smiley: 

Thanks a lot.
Also the file browser wors already.
Great improvement so far. 
Unfortunately I won't be much help in the development, but if you need help for testing or documentation I could do that.
I started a docu update a few years ago, but they never got merged or discussed ...

**Comment by prertik** [comment]
Great. Any help would be awesome since, I'm re-doing stuffs. Yeah, testing and documentation helps would be awesome too. Thanks. I'll update the project structure repository and start active development cycle tomorrow(since, my vacation ends tomorrow).

**Comment by MarcusE1W** [comment]
Cool.

I am really happy to report that I could also successfully compile it on my $99 [Piinebook](https://www.pine64.org/?page_id=3707) with ARM processor. 

I am looking forward to your updates.
